/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void colorWheelClicked(GButton source, GEvent event) { //_CODE_:colorWheel:510584:
  screen.screen = 2;
} //_CODE_:colorWheel:510584:

public void explorePalettesClicked(GButton source, GEvent event) { //_CODE_:explorePalettes:253406:
  screen.screen = 6;
} //_CODE_:explorePalettes:253406:

public void exploreColorsClicked(GButton source, GEvent event) { //_CODE_:exploreColors:713295:
  screen.screen = 10; // TURN BACK TO 4
} //_CODE_:exploreColors:713295:

public void homeClicked(GButton source, GEvent event) { //_CODE_:home:807939:
  screen.screen = 1;
} //_CODE_:home:807939:

public void savedListClicked(GButton source, GEvent event) { //_CODE_:savedList:902677:
  
} //_CODE_:savedList:902677:

public void redValueChanged(GSlider source, GEvent event) { //_CODE_:redValue:246119:
  screen.r = redValue.getValueI();
} //_CODE_:redValue:246119:

public void greenValueChanged(GSlider source, GEvent event) { //_CODE_:greenValue:235878:
  screen.g = greenValue.getValueI();
} //_CODE_:greenValue:235878:

public void blueValueChanged(GSlider source, GEvent event) { //_CODE_:blueValue:633457:
  screen.b = blueValue.getValueI();
} //_CODE_:blueValue:633457:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  colorWheel = new GButton(this, 38, 0, 200, 40);
  colorWheel.setIcon("Screenshot 2023-11-25 163910 (1).png", 1, GAlign.NORTH, GAlign.CENTER, GAlign.MIDDLE);
  colorWheel.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  colorWheel.addEventHandler(this, "colorWheelClicked");
  explorePalettes = new GButton(this, 486, 0, 257, 40);
  explorePalettes.setIcon("Screenshot 2023-11-25 164246.png", 1, GAlign.EAST, GAlign.RIGHT, GAlign.MIDDLE);
  explorePalettes.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  explorePalettes.addEventHandler(this, "explorePalettesClicked");
  exploreColors = new GButton(this, 239, 0, 247, 40);
  exploreColors.setIcon("Screenshot 2023-11-25 164243.png", 1, GAlign.EAST, GAlign.RIGHT, GAlign.MIDDLE);
  exploreColors.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  exploreColors.addEventHandler(this, "exploreColorsClicked");
  home = new GButton(this, 0, 0, 35, 40);
  home.setIcon("Screenshot 2023-11-25 170223.png", 1, GAlign.EAST, GAlign.RIGHT, GAlign.MIDDLE);
  home.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  home.addEventHandler(this, "homeClicked");
  savedList = new GButton(this, 747, 1, 45, 40);
  savedList.setIcon("Screenshot 2023-11-25 170900.png", 1, GAlign.EAST, GAlign.RIGHT, GAlign.MIDDLE);
  savedList.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  savedList.addEventHandler(this, "savedListClicked");
  redValue = new GSlider(this, 325, 420, 255, 40, 10.0);
  redValue.setLimits(35, 0, 255);
  redValue.setNumberFormat(G4P.INTEGER, 0);
  redValue.setLocalColorScheme(GCScheme.RED_SCHEME);
  redValue.setOpaque(false);
  redValue.addEventHandler(this, "redValueChanged");
  greenValue = new GSlider(this, 325, 470, 255, 40, 10.0);
  greenValue.setLimits(45, 0, 255);
  greenValue.setNumberFormat(G4P.INTEGER, 0);
  greenValue.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  greenValue.setOpaque(false);
  greenValue.addEventHandler(this, "greenValueChanged");
  blueValue = new GSlider(this, 325, 520, 255, 40, 10.0);
  blueValue.setLimits(55, 0, 255);
  blueValue.setNumberFormat(G4P.INTEGER, 0);
  blueValue.setOpaque(false);
  blueValue.addEventHandler(this, "blueValueChanged");
}

// Variable declarations 
// autogenerated do not edit
GButton colorWheel; 
GButton explorePalettes; 
GButton exploreColors; 
GButton home; 
GButton savedList; 
GSlider redValue; 
GSlider greenValue; 
GSlider blueValue; 
