/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void colorWheelClicked(GButton source, GEvent event) { //_CODE_:colorWheel:510584:
  println("colorWheel - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:colorWheel:510584:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  colorWheel = new GButton(this, 56, 32, 230, 50);
  colorWheel.setIcon("Screenshot 2023-11-24 10.39.47 AM.png", 1, GAlign.NORTH, GAlign.CENTER, GAlign.MIDDLE);
  colorWheel.setLocalColorScheme(GCScheme.EAST);
  colorWheel.addEventHandler(this, "colorWheelClicked");
}

// Variable declarations 
// autogenerated do not edit
GButton colorWheel; 
